In [1]:
import numpy as np

# ---------------- Q1 ----------------

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

# a
corrected_temperature = temperature + 2
print("Corrected temperatures:", corrected_temperature)

# b
fahrenheit = (9/5) * temperature + 32
print("Temperature in Fahrenheit:", fahrenheit)

# c
greater_than_32 = temperature[temperature > 32]
print("Temperatures greater than 32°C:", greater_than_32)

# d
count = np.sum(temperature > 32)
print("Number of readings greater than 32°C:", count)


# ---------------- Q2 ----------------

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

# a
print("\nTotal steps:", np.sum(steps))

# b
print("Mean steps:", np.mean(steps))

# c
print("Maximum steps:", np.max(steps))
print("Minimum steps:", np.min(steps))

# d
print("Total steps for each day:", np.sum(steps, axis=0))

# e
print("Total steps for each user:", np.sum(steps, axis=1))

# f
position = np.unravel_index(np.argmax(steps), steps.shape)
print("Position of maximum:", position)
print("Maximum value:", steps[position])

Corrected temperatures: [27 30 33 37 40 29 35 42]
Temperature in Fahrenheit: [ 77.   82.4  87.8  95.  100.4  80.6  91.4 104. ]
Temperatures greater than 32°C: [35 38 33 40]
Number of readings greater than 32°C: 4

Total steps: 84200
Mean steps: 7016.666666666667
Maximum steps: 9500
Minimum steps: 4500
Total steps for each day: [26500 27300 30400]
Total steps for each user: [18300 24500 14400 27000]
Position of maximum: (np.int64(3), np.int64(2))
Maximum value: 9500


In [2]:
import numpy as np

# a
original = np.array([1, 2, 3, 4, 5, 6])
print("Original:", original)

# b
subset = original[1:5]
print("\nSubset:", subset)

# c
subset[0] = 999
print("\nAfter modifying subset:")
print("Original:", original)
print("Subset:", subset)

# d
copied_array = original[1:5].copy()
copied_array[0] = 500

print("\nAfter modifying copied array:")
print("Original:", original)
print("Copied array:", copied_array)

# e
arr = np.arange(1, 13).reshape(3, 4)
print("\n3 x 4 Matrix:")
print(arr)

# f
print("\nFirst row:", arr[0])
print("Last row:", arr[-1])
print("Second column:", arr[:, 1])
print("Rows 1-2, Columns 2-3:")
print(arr[1:3, 2:4])

# g
flat_array = arr.flatten()
ravel_array = arr.ravel()

print("\nFlatten:", flat_array)
print("Ravel:", ravel_array)

# h
ravel_array[0] = 999
print("\nAfter modifying ravel:")
print(arr)

# i
flat_array[1] = 500
print("\nAfter modifying flatten:")
print("Original:")
print(arr)
print("Flattened array:", flat_array)

# j
print("\nShape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data type:", arr.dtype)

Original: [1 2 3 4 5 6]

Subset: [2 3 4 5]

After modifying subset:
Original: [  1 999   3   4   5   6]
Subset: [999   3   4   5]

After modifying copied array:
Original: [  1 999   3   4   5   6]
Copied array: [500   3   4   5]

3 x 4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2, Columns 2-3:
[[ 7  8]
 [11 12]]

Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]

After modifying ravel:
[[999   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

After modifying flatten:
Original:
[[999   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Flattened array: [  1 500   3   4   5   6   7   8   9  10  11  12]

Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


In [4]:
import numpy as np

y = np.array([40, 65, 30, 85])

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

In [5]:
XT = X.T

XTX = XT @ X

XTX_inverse = np.linalg.inv(XTX)

beta = XTX_inverse @ XT @ y

print("X.T:")
print(XT)

print("\nX.T @ X:")
print(XTX)

print("\nBeta:")
print(beta)

X.T:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

Beta:
[-0.15921454  0.14083853 10.06302242]
